version: "3.9"

services:
  goproj:
    build: ./
    command: ./goproj
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
    - DB_PASSWORD=123
  

  db:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_DB: "stoneshop"
        POSTGRES_PASSWORD: "123"
        PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5432:5432